label: Deutsch
pages:
    -
        label: The Black Hack
        author: Matthias Schaffrath
        version: '1.1'
    -
        label: Mehr Kram ("Additional Things")
        author: Matthias Schaffrath
        version: '1.2'
        filename: additional-things.md
